name: brainBreak
version: 0.1.2
description: BrainFuck interpreter written in Haskell. See more at https://github.com/s3rius/brainBreak

author: s3rius
maintainer: win10@list.ru

github: s3rius/brainBreak
license: BSD3
copyright: 2020 s3rius


extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2 && < 3
- trifecta >= 2 && < 3
- parsers >= 0.12 && < 1
- options >= 1.2 && < 1.3
- containers >= 0.6 && < 1

library:
  source-dirs: src

executables:
  bb:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainBreak

tests:
  brainBreak-test:
    source-dirs: tests
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainBreak
    - hspec >= 2.7.6 && < 3
    - hspec-discover >= 2.7.6 && < 3
