library:
  source-dirs: 
    - src
tests:
  brainBreak-test:
    source-dirs: tests
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainBreak
    - hspec >= 2.7.1 && < 2.8
copyright: 2020 s3rius
maintainer: example@example.com
dependencies:
- containers >= 0.6 && < 1
- mtl >= 2.2.2 && < 3
- trifecta >= 2 && < 3
- base >= 4.7 && < 5
- parsers >= 0.12 && < 1
- options >= 1.2 && < 1.3
name: brainBreak
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: s3rius
github: s3rius/brainBreak
license: BSD3
executables:
  brainBreak-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainBreak
description: BrainFuck interpreter written in Haskell. See more at https://github.com/s3rius/brainBreak
